{
  writeSectionStart("CLASSES");
  writeClass("ACDBDICTIONARYWDFLT","AcDbDictionaryWithDefault","ObjectDBX Classes",0,false,false);
  writeClass("TABLESTYLE","AcDbTableStyle","ObjectDBX Classes",2047,false,false);
  writeClass("DICTIONARYVAR","AcDbDictionaryVar","ObjectDBX Classes",0,false,false);
  writeClass("XRECORD","AcDbXrecord","AutoCAD 2000",0,false,false);
  writeClass("LWPOLYLINE","AcDbPolyline","AutoCAD 2000",0,false,true);
  writeClass("HATCH","AcDbHatch","AutoCAD 2000",0,false,true);
  writeClass("ACDBPLACEHOLDER","AcDbPlaceHolder","ObjectDBX Classes",0,false,false);
  writeClass("LAYOUT","AcDbLayout","ObjectDBX Classes",0,false,false);
  writeSectionEnd();
}
